pipeline {
    agent any

    tools {
        maven 'Maven3'       // Name must match Jenkins Global Tool config
        jdk 'JDK11'          // Or JDK17 depending on your setup
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Dukes14/AutoFrameworkAPI.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.xml', fingerprint: true
        }
        success {
            echo '✅ Automation executed successfully'
        }
        failure {
            echo '❌ Automation failed'
        }
    }
}
